server:
  port: 8085
  servlet:
    context-path: /interest/message
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
      name: interest-message
  datasource:
    url: jdbc:mysql://cdb-e11kt96s.cd.tencentcdb.com:10030/interest_message?useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=UTF-8&useSSL=false&jdbcCompliantTruncation=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: Wei185399
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: DatebookHikariCP
  redis:
    database: 0
    host: 42.193.113.93
    port: 6379
    password: null
    timeout: 5000ms
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000ms
  liquibase:
    change-log: classpath:database/master.xml
    enabled: true
    drop-first: false
  cloud:
    stream:
      kafka:
        binder:
          brokers: www.wkm1115.cn:9092
          auto-create-topics: true
          auto-add-partitions: true
          min-partition-count: 1
      bindings:
        message_input:
          destination: interest-message
          group: interest-message-group
          consumer:
            headerMode: raw
logging:
# 你需要存储日志的目录
  file: log/interest-message.log
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.interest.message: DEBUG
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.interest.message.model
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000